version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
cache:
  paths:
    -'/root/.m2/**/*'
artifacts:
  files:
    - target/Youtube_Paws_Spring-0.0.1-SNAPSHOT.jar